### PR TITLE
basic server test for SCRAM-SHA-256

### PR DESCRIPTION
**Pull request by slingamn**
Tested against a new Ergo implementation that isn't published yet. But this shouldn't break anything, due to `OptionalityHelper`.

### CODE REVIEW

**Comment by slingamn** [comment]
Hm. Can we exempt directories from pre-commit? If so I would actually remove 0d0f3a12a6565 as well.

**Comment by ProgVal** [comment]
https://stackoverflow.com/a/61046953/539465

**Comment by slingamn** [comment]
Hmm, 39b11e53e0d6cb51 successfully exempted `irctest/scram/` from black, but did not exempt it from mypy. I tried adding a separate exemption in mypy.ini but it didn't work. I'm out of ideas for now.

**Comment by slingamn** [comment]
Oh, I just realized this will fail its Ergo test as well until Ergo's `irctest_stable` branch is updated, since the list of supported mechanisms is hardcoded in the controller.

**Comment by ProgVal** [comment]
try using https://mypy.readthedocs.io/en/latest/command_line.html#cmdoption-mypy-exclude

**Comment by slingamn** [comment]
I merged the relevant ergo branch into `irctest_stable`, so this should pass now.

I tried several different variations of exclude rule for mypy and couldn't get it to pass, not sure what the deal is :-|

**Comment by ProgVal** [comment]
I figured it out!

```diff
diff --git a/mypy.ini b/mypy.ini
index 3e057b8..3d5dd57 100644
--- a/mypy.ini
+++ b/mypy.ini
@@ -6,6 +6,9 @@ warn_unused_configs = True
 [mypy-irctest.*]
 disallow_untyped_defs = True
 
+[mypy-irctest.scram]
+disallow_untyped_defs = False
+
 [mypy-irctest.server_tests.*]
 disallow_untyped_defs = False
```

**Comment by ProgVal** [comment]
why did you replace the nonce factory?

**Comment by slingamn** [comment]
Just aesthetics; `secrets` is the modern best practice for this. The amount of entropy is larger this way (256 bits versus 122), but it doesn't matter for any practical purpose. Chalk it down to my personal obsession with CSPRNGs.

**Comment by ProgVal** [comment]
Then send a patch upstream instead of fixing it here lol

**Pull request merged**
