### PR TITLE
add a regression test for ergochat/ergo#1928

### PR DESCRIPTION
**Pull request by slingamn**
LIST on a nonexistent channel does not get an error response.

This can't be merged yet since Ergo's irctest_stable does not pass.

### CODE REVIEW

**Comment by slingamn** [comment]
I updated Ergo's irctest_stable. I'll let you figure out what to do about Charybdis and Solanum ;-)

**Comment by progval** [comment]
Oh, hmmmm

**Comment by progval** [comment]
https://github.com/solanum-ircd/solanum/pull/326

**Comment by slingamn** [comment]
Succeeded by #165

**Pull request closed without merging**
