### PR TITLE
Don't pass a 'config' argument to the controller, only Oragono had it.

### PR DESCRIPTION
**Pull request by ProgVal**
Instead, annotate tests with the optional features they may need from the IRCd.

### CODE REVIEW

**Comment by slingamn** [comment]
I think making `CONFIG` a mutable class member risks pollution across tests? That's why I had this as a function.

**Comment by ProgVal** [comment]
I considered it, but it actually requires more effort from the clients to update it than to just redefine it. I can make it a function though.

**Comment by ProgVal** [comment]
I made it a function. It's a little more verbose, but better safe than sorry.

**Comment by slingamn** [comment]
Very nice! shipit

**Pull request merged**
