### PR TITLE
Lusers: deduplicate asserts + add more asserts + fix inspircd support

### PR DESCRIPTION
**Pull request by ProgVal**
There are three commits, I recommend reading them individually

### CODE REVIEW

**Comment by slingamn** [comment]
Ship it! `253 RPL_LUSERUNKNOWN` is RFC1459, but if Inspircd doesn't implement it I guess that makes it optional :-|

**Comment by ProgVal** [comment]
Well the spec doesn't say it's mandatory, therefore it's optional.

**Comment by slingamn** [comment]
Interesting:

>In processing an LUSERS message, the server sends a set of replies from RPL_LUSERCLIENT, RPL_LUSEROP, RPL_USERUNKNOWN, RPL_LUSERCHANNELS and RPL_LUSERME.  When replying, a server must send back                          RPL_LUSERCLIENT and RPL_LUSERME.  The other replies are only sent back if a non-zero count is found for them.

I checked their testnet and Inspircd will in fact send 253 if there is an open, unregistered connection. (But IIRC it takes up to a full second for that status to be recognized?)

**Comment by slingamn** [comment]
So this suggests that for RPL_LUSERUNKNOWN, at least, the correct default is 0 rather than None.

**Comment by ProgVal** [comment]
Hmm it's ambiguous at best.

**Pull request merged**
