### PR TITLE
Use pytest as a test runner instead of unit test

### PR DESCRIPTION
**Pull request by ProgVal**
'./test <controller> -s spec1 -s spec2' becomes:
'pytest --controller <controller> -k "spec1 or spec2"'

This uses pytest's test selection, which allows finer selection of which tests
to run (for example, it will allow running all tests but those requiring one
feature or combination of features).
It also allows running only a particular test (or set of test) by
filtering on their name or file name.

pytest also shows a much nicer output while testing (grouped by file,
percentage of tests run, manages the verbosity); and it captures all the output
and only shows it if the test fails, which makes --show-io irrelevant.

### CODE REVIEW

**Comment by slingamn** [comment]
sgtm, will try this branch out on my system later

**Comment by slingamn** [comment]
How do I run the tests? On Ubuntu 20.04, I get:

```
$ py.test-3 --controller oragono
Exit: Cannot import module oragono
```

**Comment by slingamn** [comment]
I guess `python3 -m pytest` is a robust way to execute these, e.g., in the context of a Makefile?

**Comment by ProgVal** [comment]
I use `pytest` directly, but `python3 -m pytest` sounds more robust indeed

**Comment by ProgVal** [comment]
> I have two test failures on Oragono: `JoinTestCase.testInviteNonExistingChannelTransmitted` and `JoinTestCase.testInviteNonExistingChannelEchoed`.

Run with `-k not deprecated`

**Comment by slingamn** [comment]
Cool, I can add that to the makefile when the time comes.

**Comment by slingamn** [comment]
Belatedly, ship it!

**Pull request merged**
