### PR TITLE
Check for 'U' ELIST param in testListUsers

### PR DESCRIPTION
**Pull request by mitchr**

### CODE REVIEW

**Comment by progval** [comment]
Good catch, thanks!

**Comment by progval** [comment]
Looks like you found a bug in Ergo. They'll need to fix it before I can merge this PR

**Comment by progval** [comment]
https://github.com/ergochat/ergo/pull/1934

**Comment by slingamn** [comment]
I updated ergo's `irctest_stable` to 504cc44, which includes this fix.

**Comment by progval** [comment]
Thanks again, @mitchr

**Pull request merged**
